import type { Event } from "@/lib/types"

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Annual Tech Symposium",
    description: "Join us for a day of tech talks, workshops, and networking opportunities with industry leaders.",
    date: "2025-06-15",
    time: "10:00 AM",
    location: "Main Auditorium",
    category: "Technology",
    collegeName: "Stanford University",
    collegeId: "stanford",
    image: "/assets/hackathon.jpg?height=200&width=400&text=Tech+Symposium",
    isStarred: false,
  },
  {
    id: "2",
    title: "Cultural Festival",
    description: "Celebrate diversity with performances, food stalls, and cultural exhibitions from around the world.",
    date: "2025-07-10",
    time: "5:00 PM",
    location: "College Grounds",
    category: "Cultural",
    collegeName: "MIT",
    collegeId: "mit",
    image: "/assets/hackathon2.png?height=200&width=400&text=Cultural+Festival",
    isStarred: true,
  },
  {
    id: "3",
    title: "Career Fair 2025",
    description: "Meet recruiters from top companies and explore career opportunities in various fields.",
    date: "2025-05-20",
    time: "9:00 AM",
    location: "Business School",
    category: "Career",
    collegeName: "Harvard University",
    collegeId: "harvard",
    image: "/placeholder.svg?height=200&width=400&text=Career+Fair",
    isStarred: false,
  },
  {
    id: "4",
    title: "Alumni Meetup",
    description: "Network with alumni and learn from their experiences in different industries and roles.",
    date: "2025-04-05",
    time: "6:00 PM",
    location: "College Cafeteria",
    category: "Networking",
    collegeName: "UC Berkeley",
    collegeId: "berkeley",
    image: "/placeholder.svg?height=200&width=400&text=Alumni+Meetup",
    isStarred: true,
  },
  {
    id: "5",
    title: "Research Symposium",
    description: "Explore cutting-edge research from various departments and interact with leading researchers.",
    date: "2025-08-12",
    time: "11:00 AM",
    location: "Science Building",
    category: "Academic",
    collegeName: "Stanford University",
    collegeId: "stanford",
    image: "/placeholder.svg?height=200&width=400&text=Research+Symposium",
    isStarred: false,
  },
  {
    id: "6",
    title: "Music Festival",
    description: "Enjoy performances from talented musicians across campus and guest artists from around the country.",
    date: "2025-09-18",
    time: "3:00 PM",
    location: "University Amphitheater",
    category: "Entertainment",
    collegeName: "Yale University",
    collegeId: "yale",
    image: "/placeholder.svg?height=200&width=400&text=Music+Festival",
    isStarred: false,
  },
  {
    id: "7",
    title: "Hackathon 2025",
    description:
      "A 48-hour coding competition where students collaborate to build innovative solutions to real-world problems.",
    date: "2025-10-05",
    time: "9:00 AM",
    location: "Engineering Building",
    category: "Technology",
    collegeName: "MIT",
    collegeId: "mit",
    image: "/placeholder.svg?height=200&width=400&text=Hackathon",
    isStarred: false,
  },
  {
    id: "8",
    title: "Sports Tournament",
    description: "Cheer for your favorite teams in this inter-college sports competition featuring multiple sports.",
    date: "2025-11-12",
    time: "10:00 AM",
    location: "Sports Complex",
    category: "Sports",
    collegeName: "UCLA",
    collegeId: "ucla",
    image: "/placeholder.svg?height=200&width=400&text=Sports+Tournament",
    isStarred: false,
  },
  {
    id: "9",
    title: "Entrepreneurship Summit",
    description: "Learn from successful entrepreneurs and investors about starting and scaling businesses.",
    date: "2025-12-03",
    time: "2:00 PM",
    location: "Business Center",
    category: "Business",
    collegeName: "Harvard University",
    collegeId: "harvard",
    image: "/placeholder.svg?height=200&width=400&text=Entrepreneurship+Summit",
    isStarred: true,
  },
]
